return {
	BodyColors = {
		Head = Color3.fromRGB(255, 180, 0),

		UpperTorso = Color3.fromRGB(255, 120, 0),
		LowerTorso = Color3.fromRGB(255, 60, 0),

		LeftUpperArm = Color3.fromRGB(255, 180, 0),
		LeftLowerArm = Color3.fromRGB(255, 120, 0),
		LeftHand = Color3.fromRGB(255, 60, 0),

		RightUpperArm = Color3.fromRGB(255, 180, 0),
		RightLowerArm = Color3.fromRGB(255, 120, 0),
		RightHand = Color3.fromRGB(255, 60, 0),

		LeftUpperLeg = Color3.fromRGB(255, 120, 0),
		LeftLowerLeg = Color3.fromRGB(255, 60, 0),
		LeftFoot = Color3.fromRGB(255, 220, 0),

		RightUpperLeg = Color3.fromRGB(255, 120, 0),
		RightLowerLeg = Color3.fromRGB(255, 60, 0),
		RightFoot = Color3.fromRGB(255, 220, 0),
	},
}