return {
	BodyColors = {
		Head = Color3.fromRGB(255, 255, 255),
		UpperTorso = Color3.fromRGB(250, 250, 250),
		LowerTorso = Color3.fromRGB(245, 245, 245),
		LeftUpperArm = Color3.fromRGB(252, 252, 252),
		LeftLowerArm = Color3.fromRGB(248, 248, 248),
		LeftHand = Color3.fromRGB(255, 255, 255),
		RightUpperArm = Color3.fromRGB(252, 252, 252),
		RightLowerArm = Color3.fromRGB(248, 248, 248),
		RightHand = Color3.fromRGB(255, 255, 255),
		LeftUpperLeg = Color3.fromRGB(245, 245, 245),
		LeftLowerLeg = Color3.fromRGB(240, 240, 240),
		LeftFoot = Color3.fromRGB(255, 220, 130),
		RightUpperLeg = Color3.fromRGB(245, 245, 245),
		RightLowerLeg = Color3.fromRGB(240, 240, 240),
		RightFoot = Color3.fromRGB(255, 220, 130),
	},

	ShirtAsset = 0,
	PantsAsset = 0,
}