return {
	BodyColors = {
		Head = Color3.fromRGB(60, 60, 100),
		UpperTorso = Color3.fromRGB(50, 50, 90),
		LowerTorso = Color3.fromRGB(40, 40, 80),
		LeftUpperArm = Color3.fromRGB(55, 55, 95),
		LeftLowerArm = Color3.fromRGB(45, 45, 85),
		LeftHand = Color3.fromRGB(70, 70, 110),
		RightUpperArm = Color3.fromRGB(55, 55, 95),
		RightLowerArm = Color3.fromRGB(45, 45, 85),
		RightHand = Color3.fromRGB(70, 70, 110),
		LeftUpperLeg = Color3.fromRGB(40, 40, 80),
		LeftLowerLeg = Color3.fromRGB(35, 35, 70),
		LeftFoot = Color3.fromRGB(50, 50, 100),
		RightUpperLeg = Color3.fromRGB(40, 40, 80),
		RightLowerLeg = Color3.fromRGB(35, 35, 70),
		RightFoot = Color3.fromRGB(50, 50, 100),
	},

	ShirtAsset = 0,
	PantsAsset = 0,
}