return {
	BodyColors = {
		Head = Color3.fromRGB(70, 150, 255),

		UpperTorso = Color3.fromRGB(80, 170, 255),
		LowerTorso = Color3.fromRGB(255, 255, 255),

		LeftUpperArm = Color3.fromRGB(70, 150, 255),
		LeftLowerArm = Color3.fromRGB(255, 255, 255),
		LeftHand = Color3.fromRGB(255, 255, 255),

		RightUpperArm = Color3.fromRGB(70, 150, 255),
		RightLowerArm = Color3.fromRGB(255, 255, 255),
		RightHand = Color3.fromRGB(255, 255, 255),

		LeftUpperLeg = Color3.fromRGB(220, 220, 220),
		LeftLowerLeg = Color3.fromRGB(180, 180, 180),
		LeftFoot = Color3.fromRGB(80, 80, 80),

		RightUpperLeg = Color3.fromRGB(220, 220, 220),
		RightLowerLeg = Color3.fromRGB(180, 180, 180),
		RightFoot = Color3.fromRGB(80, 80, 80),
	},
}