return {
	BodyColors = {
		Head = Color3.fromRGB(255, 255, 255),

		UpperTorso = Color3.fromRGB(245, 245, 245),
		LowerTorso = Color3.fromRGB(235, 235, 235),

		LeftUpperArm = Color3.fromRGB(255, 255, 255),
		LeftLowerArm = Color3.fromRGB(245, 245, 245),
		LeftHand = Color3.fromRGB(240, 240, 240),

		RightUpperArm = Color3.fromRGB(255, 255, 255),
		RightLowerArm = Color3.fromRGB(245, 245, 245),
		RightHand = Color3.fromRGB(240, 240, 240),

		LeftUpperLeg = Color3.fromRGB(235, 235, 235),
		LeftLowerLeg = Color3.fromRGB(225, 225, 225),
		LeftFoot = Color3.fromRGB(255, 180, 80),

		RightUpperLeg = Color3.fromRGB(235, 235, 235),
		RightLowerLeg = Color3.fromRGB(225, 225, 225),
		RightFoot = Color3.fromRGB(255, 180, 80),
	},
}