return {
	BodyColors = {
		Head = Color3.fromRGB(40, 0, 80),
		UpperTorso = Color3.fromRGB(30, 0, 70),
		LowerTorso = Color3.fromRGB(20, 0, 60),
		LeftUpperArm = Color3.fromRGB(35, 0, 75),
		LeftLowerArm = Color3.fromRGB(25, 0, 65),
		LeftHand = Color3.fromRGB(50, 10, 90),
		RightUpperArm = Color3.fromRGB(35, 0, 75),
		RightLowerArm = Color3.fromRGB(25, 0, 65),
		RightHand = Color3.fromRGB(50, 10, 90),
		LeftUpperLeg = Color3.fromRGB(25, 0, 60),
		LeftLowerLeg = Color3.fromRGB(20, 0, 50),
		LeftFoot = Color3.fromRGB(30, 0, 70),
		RightUpperLeg = Color3.fromRGB(25, 0, 60),
		RightLowerLeg = Color3.fromRGB(20, 0, 50),
		RightFoot = Color3.fromRGB(30, 0, 70),
	},

	ShirtAsset = 0,
	PantsAsset = 0,
}